import { Box, Button } from "@mui/material";
import { Container } from "@mui/system";
import Axios from "axios";
import Head from "next/head";
import { ApiConstants } from "../../constants/api.constants";
import { Livro } from "../../models/Livro";
import styles from "./excluir-livro.module.scss";

type ExcluirLivroProps = {
  onClose: () => void;
  onAtualizarLista: () => void;
  livro: Livro;
};

export function ExcluirLivro({
  onClose,
  onAtualizarLista,
  livro,
}: ExcluirLivroProps) {
  async function excluirLivro() {
    const response = await Axios.delete(
      `${ApiConstants.API_LIVROS}/${livro.id}`
    );

    if (response.status == 200) {
      onAtualizarLista();
      onClose();
    }
  }

  return (
    <Container maxWidth="sm" className={styles.container}>
      <Head>
        <title>Excluir Livro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        <p className={styles.texto}>
          Tem certeza que deseja excluir o livro <b>{`${livro.titulo}`}</b>?
        </p>
        <div className={styles.botoes}>
          <Button onClick={excluirLivro}>Sim</Button>
          <Button onClick={onClose}>Cancelar</Button>
        </div>
      </Box>
    </Container>
  );
}
